openapi: "3.0.1"
info:
  title: "health-decleration-app"
  version: "2023-10-26T00:36:12Z"
servers:
- url: "https://sm7tgtc38h.execute-api.ap-southeast-1.amazonaws.com/dev"

      
tags:
 - name: User Health Declaration
 - name: Options

paths:
  /users:
    get:
      parameters:
        - name: fullname
          description: either fullname or nric needs to be provided
          in: query
          schema:
            type: string
            example: Alice Tan

        - name: nric
          description: either fullname or nric needs to be provided
          in: query
          schema:
            type: string
            example: S1234567M
      tags:
        - User Health Declaration
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserHealthData"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${getUserHealthInfo_uri}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
    post:
      tags:
        - User Health Declaration
      requestBody:
        $ref: '#/components/requestBodies/UserHealthData'
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: string
                example: "Updated successfully!"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${addUserHealthInfo_uri}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
    
    options:
      tags:
        - Options
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS,PATCH,POST'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"

components:
  schemas:
    Empty:
      type: object
    HealthDeclaration:
      type: object
      properties:
        temperature:
          type: number
          example: 36.3
        symptons:
          type: object
          properties:
            cough: 
              type: boolean
            smellAndTasteImpairment: 
              type: boolean
            fever: 
              type: boolean
            breathingDifficulties: 
              type: boolean
            bodyAches: 
              type: boolean
            headAches: 
              type: boolean
            fatigue: 
              type: boolean
            soreThroat: 
              type: boolean
            diarrhea: 
              type: boolean
            runnyNose: 
              type: boolean
        contactWithin14Days: 
          type: boolean
    UserHealthData:
      type: object
      properties:
        fullname:
          type: string
          example: Alice Tan
        nric:
          type: string
          example: S1234567M
        phone:
          type: string
          example: "+65 12345678"
        healthDeclarations:
          type: array
          items: 
            $ref: '#/components/schemas/HealthDeclaration'
    UserHealthDataRequestBody:
      type: object
      properties:
        fullname:
          type: string
          example: Alice Tan
        nric:
          type: string
          example: S1234567M
        phone:
          type: string
          example: "+65 12345678"
        healthDetails:
            $ref: '#/components/schemas/HealthDeclaration'

  requestBodies:
    UserHealthData:
      required: true
      content: 
        application/json:
          schema:
            $ref: '#/components/schemas/UserHealthDataRequestBody'

  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"